import logging
import os
from pathlib import Path

from fastapi import UploadFile
from sqlalchemy.orm import Session

from app.repositories.resumes import create_resume_record, update_resume_processing_result
from app.services.file_storage import save_upload
from app.services.pii_scrubber import scrub_pii
from app.services.resume_analyzer import analyze_resume_text
from app.services.resume_parser import extract_text
from app.services.resume_profile_pipeline import persist_resume_profile
from app.services.vacancy_warmup import trigger_warmup_for_resume

logger = logging.getLogger(__name__)

# User-supplied filenames frequently contain PII (e.g. "Иванов_И_И_резюме.pdf").
# We only keep the extension for the UI fallback — the real on-disk name is a uuid
# generated by save_upload() and the file itself is deleted right after analysis.
_ALLOWED_EXTS = {".pdf", ".docx"}


def _sanitize_display_filename(original: str | None) -> str:
    ext = Path(original or "").suffix.lower()
    if ext not in _ALLOWED_EXTS:
        ext = ""
    return f"resume{ext}"


def _delete_file(path: str | None) -> None:
    if not path:
        return
    try:
        os.unlink(path)
    except OSError as exc:
        logger.info("uploaded_file_already_gone path=%s err=%s", path, exc)


def process_resume_upload(db: Session, *, user_id: int, upload: UploadFile, content: bytes):
    storage_path = save_upload(content, upload.filename or "resume")
    resume = create_resume_record(
        db,
        user_id=user_id,
        original_filename=_sanitize_display_filename(upload.filename),
        content_type=upload.content_type or "application/octet-stream",
        storage_path=storage_path,
    )

    try:
        resume = update_resume_processing_result(db, resume, status="processing")
        extracted_text = extract_text(content, resume.content_type)
        if not extracted_text.strip():
            raise ValueError("Could not extract text from the uploaded resume")

        scrubbed_text, counters = scrub_pii(extracted_text)
        logger.info("pii_scrubbed resume_id=%s counters=%s", resume.id, counters)

        resume = update_resume_processing_result(
            db,
            resume,
            status="processing",
        )
        analysis = analyze_resume_text(scrubbed_text)
        persist_resume_profile(db, resume_id=resume.id, user_id=user_id, profile=analysis)
        _delete_file(storage_path)
        resume.storage_path = None
        completed = update_resume_processing_result(
            db,
            resume,
            status="completed",
            analysis=analysis,
        )
        trigger_warmup_for_resume(user_id=user_id, resume_id=completed.id)
        return completed
    except Exception as error:
        _delete_file(storage_path)
        resume.storage_path = None
        return update_resume_processing_result(
            db,
            resume,
            status="failed",
            error_message=str(error),
        )
